name: Deploy All APIs

on:
  push:
    branches:
      - main
jobs:
  channel-api:
    name: Deploy API doc on Bump
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Deploy API documentation
        uses: bump-sh/github-action@v1
        with:
          doc: 883926e0-674c-42e8-b9f6-8b1466744762
          token: ${{secrets.BUMP_TOKEN}}
          file: Channel/channel.json

  commerce-api:
    name: Deploy API doc on Bump
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Deploy API documentation
        uses: bump-sh/github-action@v1
        with:
          doc: 8036dc9e-c2ff-4d92-816e-3fa4535ac1f8
          token: ${{secrets.BUMP_TOKEN}}
          file: Commerce/commerce.json

  pos-api:
    name: Deploy API doc on Bump
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Deploy API documentation
        uses: bump-sh/github-action@v1
        with:
          doc: 402c4109-dbee-4857-9ee1-9917a71a676e
          token: ${{secrets.BUMP_TOKEN}}
          file: Restaurant POS/pos.json

  retail-api:
    name: Deploy API doc on Bump
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Deploy API documentation
        uses: bump-sh/github-action@v1
        with:
          doc: 511b3514-731a-4094-bfc0-0537b953a253
          token: ${{secrets.BUMP_TOKEN}}
          file: Retail POS/retail.json

 
 
